chore: test-ci runs also tests for the server side app

diff --git a/script/test-ci b/script/test-ci
--- a/script/test-ci
+++ b/script/test-ci
@@ -2,6 +2,16 @@
 
 source ./script/lib/server
 
+# Run test for the server side application
+mocha --compilers coffee:coffee-script --reporter spec server/test
+
+# ..check if it pass
+if [ $? -ne 0 ]; then
+  echo "Failed!"
+  exit 1
+fi
+
+# ..run other specs
 startServer
 grunt test:ci
 stopServer
